import type { BlogPostSection } from "@/content/blog/types";

export const articleBody = {
  sections: [
    {
      type: "p",
      text: "Churn (abonelik iptali), MRR’ın en doğrudan düşmanıdır; ancak tüm churn aynı değildir. Voluntary (müşteri isteği) ile involuntary (ödeme başarısız) ayrımı olmadan «iptal oranımız %4» demek anlamsızdır. Shopify ve D2C abonelik operatörleri için bu yazı, iptalleri azaltan on uygulanabilir yolu iş etkisi, örnek ve metriklerle listeler — teorik churn formülü değil, saha taktikleri.",
    },
    {
      type: "h2",
      text: "Churn’ü doğru okumak: neden önce metrik?",
    },
    {
      type: "p",
      text: "Logo churn (abone sayısı) ile revenue churn (MRR) farklı hikâye anlatır. Düşük ARPU’lu plan iptali logo churn’ü şişirirken MRR etkisi küçük kalabilir. Net MRR churn, expansion ile birlikte okunmalıdır.",
    },
    {
      type: "h2",
      text: "10 etkili yol",
    },
    {
      type: "h3",
      text: "1. Voluntary ve involuntary churn’ü ayırın",
    },
    {
      type: "p",
      text: "Ayrı dashboard, ayrı müdahale. Ödeme kaynaklı churn’de dunning; istekli iptalde değer ve kurtarma teklifi. Türkiye supplement markasında bu ayrım involuntary müdahaleyi netleştirdi, recovery %34’ten %41’e çıktı.",
    },
    {
      type: "h3",
      text: "2. Duraklatma (pause) sunun",
    },
    {
      type: "p",
      text: "«İptal» yerine «1 ay duraklat» voluntary churn’ü düşürür. Pet food ve kozmetikte özellikle etkilidir. Duraklatılan abone MRR politikasına göre sayılır — finans ve operasyon aynı kuralı kullanır.",
    },
    {
      type: "h3",
      text: "3. İptal akışında kurtarma",
    },
    {
      type: "p",
      text: "Anket → kişiselleştirilmiş teklif (indirim değil: sıklık düşürme, farklı ürün, destek görüşmesi). İki adımlı iptal, bir adımlıye göre daha düşük tam iptal oranı verir (A/B ile doğrulayın).",
    },
    {
      type: "h3",
      text: "4. Dunning ve kart güncelleme",
    },
    {
      type: "p",
      text: "Retry takvimi + SMS/e-posta + müşteri panelinde kart güncelleme. RELY Subs + Craftgate/İyzico token akışı. Başarısız ödeme kaynaklı churn’ün yarısından fazlası kurtarılabilir bandda.",
    },
    {
      type: "h3",
      text: "5. Değer iletişimi (yenileme öncesi)",
    },
    {
      type: "p",
      text: "Teslimat öncesi «yarın yenileniyor» değil, «bu dönem kazanımın» mesajı: kullanım ipucu, içerik, sadakat puanı. Bildirim spam değil, ritim hatırlatması.",
    },
    {
      type: "h3",
      text: "6. Plan yükseltme ve expansion",
    },
    {
      type: "p",
      text: "Memnun aboneyi büyütmek, kaybedileni tutmaktan ucuzdur. 2.–3. ay upsell: sıklık artışı, büyük paket, çapraz ürün. Expansion MRR net churn’ü düşürür.",
    },
    {
      type: "h3",
      text: "7. Ön ödemeli plan teşviki",
    },
    {
      type: "p",
      text: "3/6/12 ay peşin ödeme, voluntary churn’ü geciktirir ve nakit akışını güçlendirir. İptal penceresi şeffaf yazılmalı.",
    },
    {
      type: "h3",
      text: "8. Destek proaktif müdahale",
    },
    {
      type: "p",
      text: "Son teslimattan 45 gün geçmiş, ödeme başarısız veya sık sık duraklatan segmente proaktif ulaşım. CRM’de «churn risk» skoru basit kurallarla başlar.",
    },
    {
      type: "h3",
      text: "9. Lojistik ve ürün sürprizini sıfırlayın",
    },
    {
      type: "p",
      text: "Geç kargo, hasarlı paket, yanlış SKU voluntary churn’ün sessiz nedenidir. Teslimat SLA ve pick-pack doğruluğu churn KPI’sına bağlanmalı.",
    },
    {
      type: "h3",
      text: "10. Cohort analizi ve kök neden",
    },
    {
      type: "p",
      text: "Edinme kanalı, plan, indirimli giriş cohort’ları ayrı churn eğrileri. «Hangi cohort ölüyor?» sorusu pazarlama ve ürün kararını besler.",
    },
    {
      type: "h2",
      text: "Yaygın hatalar",
    },
    {
      type: "p",
      text: "Churn’ü yalnızca indirimle durdurmak ARPU’yu eritir. Pause olmadan zorunlu iptal tek yol bırakmak. Başarısız ödemeyi «müşteri vazgeçti» saymak.",
    },
    {
      type: "h2",
      text: "İzlenmesi gereken metrikler",
    },
    {
      type: "ul",
      items: [
        "Gross ve net MRR churn",
        "Voluntary / involuntary logo churn",
        "Pause oranı ve pause sonrası reaktivasyon",
        "İptal akışı kurtarma oranı",
        "Recovery rate",
        "Expansion MRR",
        "Churn nedeni dağılımı (anket)",
      ],
    },
    {
      type: "p",
      text: "On taktik tek başına sihir değil; disiplinli ölçüm ve ayrı müdahale ile birleştiğinde MRR tabanı korunur. Churn sıfırlanmaz, yönetilir.",
    },
    {
      type: "h2",
      text: "On taktik nasıl bir arada çalışır?",
    },
    {
      type: "p",
      text: "Duraklatma + iptal kurtarma + dunning üçlüsü, voluntary ve involuntary churn’ü aynı anda hedefler. Sadece birini uygulamak kısmi iyileşme verir. Öncelik sırası: önce involuntary (hemen MRR korur), sonra voluntary (ömür uzatır).",
    },
    {
      type: "p",
      text: "90 günlük sprint: hafta 1–2 dunning, hafta 3–4 pause ve iptal akışı, hafta 5–8 expansion ve bildirim. Her hafta net MRR churn ve churn nedeni raporu.",
    },
    {
      type: "h3",
      text: "Türkiye pazarına özel iletişim",
    },
    {
      type: "p",
      text: "SMS açılma oranı e-postadan yüksek; başarısız ödeme ve yenileme hatırlatmasında NetGSM entegrasyonu kritik. Mesajlar kısa, marka adı görünür, self-servis link tek tık.",
    },
    {
      type: "h2",
      text: "Churn hedefi koymak",
    },
    {
      type: "p",
      text: "Olgun abonelik işletmesinde aylık logo churn %4–7 bandı görülebilir; net MRR churn expansion ile <%3 hedeflenir. Erken aşamada churn yüksek olabilir; cohort olgunlaştıkça hedef sıkılaştırılır.",
    },
    {
      type: "p",
      text: "Churn’ü sıfırlama hedefi gerçekçi değildir; yönetime «yönetilen churn» ve «kurtarılan MRR» dili ile sunulmalıdır.",
    },
    { type: "h2", text: "Her yolun ölçümü" },
    { type: "p", text: "Duraklatma: pause oranı, pause sonrası 90 gün retention. İptal kurtarma: iptal akışında kabul edilen teklif %. Dunning: recovery rate. Expansion: expansion MRR / başlangıç MRR." },
    { type: "p", text: "On yol uygulanırken tek bir «churn projesi» owner’ı ve 90 günlük KPI tablosu şart; aksi halde 3. ayda enerji söner." },
    { type: "h3", text: "Kahve, supplement, kozmetik farkı" },
    { type: "p", text: "Kahvede churn çoğunlukla «sıkıldım / çeşit»; çeşit rotasyonu voluntary churn’ü düşürür. Supplement’te «işe yaramadı»; içerik ve kullanım rehberi. Kozmetikte «alerji / beklenti»; destek ve iade politikası." },
    { type: "p", text: "Involuntary churn supplement’te daha yüksek olabilir; dunning önceliği bu dikeyde 1. sırada." },
    { type: "h2", text: "RELY operasyon seti ile uygulama" },
    { type: "p", text: "Pause, iptal anketi, dunning, storefront kart güncelleme ve bildirimler RELY’de tek akış; Shopify siparişleri senkron. Operatör Excel yerine panel kullanır; churn müdahalesi gecikmez." },
    { type: "p", text: "Net MRR churn <%3 hedefi olgun işletme için gerçekçidir; erken aşamada önce recovery ve pause metriklerini sağlamlaştırın." },
    { type: "h2", text: "Önceliklendirme matrisi" },
    { type: "p", text: "Etki × çaba: dunning ve pause yüksek etki, orta çaba; proaktif destek yüksek etki, yüksek çaba. İlk 30 gün dunning + pause, sonraki 60 gün iptal kurtarma + expansion." },
    { type: "p", text: "Churn nedeni «fiyat» ise indirim değil plan düşürme veya sıklık azaltma sunulur; ARPU contraction kabul edilir, tam churn’den iyidir." },
    { type: "p", text: "Shopify segment: son 14 günde destek ticket açan aboneler «risk» — proaktif e-posta." },
    { type: "p", text: "A/B: tek adımlı vs çok adımlı iptal; kazanan varyant tüm trafiğe alınır." },
    { type: "p", text: "Yıllık board sunumu: net MRR churn trendi ve on taktikten hangisinin en çok katkı verdiği." },
    { type: "h2", text: "Churn yönetiminde operatör özeti" },
    { type: "p", text: "On yol birlikte uygulandığında net MRR churn düşer; tek taktik sihir değildir. Voluntary ve involuntary ayrımı, pause, iptal kurtarma, dunning, expansion, bildirim, lojistik, cohort analizi ve proaktif destek — hepsi ölçülür." },
    { type: "p", text: "Türkiye D2C’de SMS ve şeffaf iptal politikası güven oluşturur. RELY Subs operasyon seti, Shopify/İkas mağazasında bu taktikleri hızla devreye almanızı sağlar." },
    { type: "p", text: "Churn sıfırlanmaz; doğru yönetildiğinde MRR tabanı korunur ve LTV büyür." },
    { type: "p", text: "İptal sonrası anket zorunlu değilse bile «neden» tek seçim sorulmalı; veri kalitesi artar." },
    { type: "p", text: "Operatör notu: metrik tanımlarını ekip içi wiki’de kilitleyin; yeni çalışan onboarding’inde aynı LTV/MRR/churn sözlüğü kullanılsın." },
    { type: "p", text: "Shopify Flow veya harici otomasyon, RELY webhook’larıyla çakışmamalı; çift e-posta müşteri güvenini zedeler." },
    { type: "p", text: "Büyüme toplantısında «bu ay kaç abone» yerine «net MRR ne kadar büyüdü, churn nedenleri ne» sorulmalıdır." },
    { type: "p", text: "Türkiye’de kargo performansı abonelik NPS’ini doğrudan etkiler; lojistik partner quarterly review abonelik KPI’sına bağlanmalıdır." },
    { type: "p", text: "RELY Subs müşteri storefront’u mobil trafiğe göre optimize edilmeli; kart güncelleme ve pause işlemleri üç tıkta tamamlanmalıdır." },
    { type: "p", text: "Churn azaltma «tek seferlik kampanya» değildir; ürün, operasyon ve tahsilatın sürekli iyileştirmesidir. On taktik checklist olarak duvarınızda kalabilir." },
    { type: "p", text: "Win-back kampanyası yalnızca 60+ gün önce iptal edenlere; aktif aboneye indirim churn'ü artırır." },
    { type: "p", text: "Ürün değişikliği (formül güncelleme) voluntary churn tetikler; önceden e-posta ve «aynı fiyat» garantisi." },
    { type: "p", text: "Destek CSAT düşük segment churn riski; haftalık liste." },
    { type: "p", text: "Churn projesi OKR: net MRR churn -%0,5 çeyrek hedefi örnek." },
    { type: "p", text: "On taktikten hangisi bu çeyrek öncelik — tek sayfa roadmap." },
    { type: "p", text: "On taktik, churn'ü sıfırlamaz ama MRR tabanını korur; voluntary ve involuntary ayrımıyla önceliklendirin. RELY pause, dunning ve storefront bu yolları hızlandırır." },
    { type: "p", text: "Operatörler için altın kural: abonelik metrikleri (MRR, churn, LTV, recovery) tek tanımlı dashboard'da haftalık okunur; Excel dağınıklığı karar geciktirir." },
    { type: "p", text: "Türkiye ödeme ve kargo gerçekleri, global abonelik playbook'unu olduğu gibi kopyalamayı engeller; yerel token, SMS ve SLA ile kalibre edin." },
    { type: "p", text: "RELY Subs, Shopify ve İkas mağazanıza headless abonelik katmanı ekler; Craftgate ve İyzico tahsilat, dunning ve müşteri storefront'u operasyonu tekilleştirir." },
    { type: "p", text: "Churn toplantısı gündemi: önce involuntary kuyruk, sonra voluntary neden kodları, sonra expansion fırsatı." },
    { type: "p", text: "«Fiyat» churn'ünde anket + plan düşürme; «ürün beğenmedim» churn'ünde içerik veya SKU değişimi." },
    { type: "p", text: "Pause kullanımı %5–15 bandı sağlıklı olabilir; %0 pause zorunlu iptali artırır." },
    { type: "p", text: "Net MRR churn hedefi yönetimle çeyreklik anlaşılır; pazarlama tek başına sorumlu tutulmaz." },
    { type: "p", text: "Bu rehberdeki taktikler, Shopify ve İkas üzerinde çalışan D2C abonelik operatörleri için saha deneyimine dayanır; metrik tanımlarınızı ekip içinde sabitleyip RELY Subs paneli ile haftalık ritim kurduğunuzda MRR, LTV ve recovery birlikte iyileşir. Tek seferlik satışa göre abonelikte kazanç, öngörülebilir taban gelir ve düşük net churn'de görünür." },
    { type: "p", text: "Özet: On yol voluntary ve involuntary churn'ü ayrı yönetir; pause, iptal kurtarma, dunning, expansion ve cohort analizi net MRR churn'ü düşürür. RELY operasyon seti Shopify mağazasında hızlı devreye alınır." },
    { type: "p", text: "Checklist maddelerini 30 günlük sprint'e bölün; sahip atayın; haftalık durum toplantısında MRR bridge ve churn nedeni okunur." },
    { type: "p", text: "Shopify D2C operatörü olarak abonelik, «eklenti» değil iş modeli katmanıdır; metrik disiplini olmadan büyüme sürdürülemez." },
    { type: "p", text: "Pazarlama, finans ve operasyon aynı toplantıda MRR hareket tablosunu okumadığında abonelik projesi parçalanır; haftalık 30 dakika «abonelik council» bu riski azaltır." },
    { type: "p", text: "Türkiye'de SMS ve e-posta birlikte kullanıldığında recovery ve churn müdahalesi güçlenir; yalnızca e-posta tek başına yetersiz kalır." },
    { type: "p", text: "RELY Subs: Shopify/İkas ürün ve sipariş senkronu, Craftgate/İyzico token tahsilatı, dunning, Mailgun/NetGSM bildirimleri ve müşteri storefront — operatörün tekrarlayan gelir altyapısı tek panelde toplanır." },
    { type: "p", text: "Yazı sonu hatırlatma: abonelik operasyonunda ölçmediğiniz metrik yönetemezsiniz; MRR bridge, cohort LTV, voluntary/involuntary churn ayrımı ve recovery rate dörtlüsü olmadan büyüme kararları kör kalır. RELY Subs bu dörtlüyü destekleyen headless katmandır — mevcut Shopify veya İkas mağazanızı değiştirmeden tekrarlayan gelir disiplinini kurun." },
    { type: "p", text: "Uygulama checklist'indeki maddeleri öncelik sırasına koyun; ilk 14 günde ödeme ve metrik altyapısı, sonraki 30 günde churn ve LTV müdahaleleri devreye girsin." },
    { type: "p", text: "İleri okuma: MRR bridge ve cohort retention raporlarını aylık kapanışta finans ve pazarlama ile birlikte gözden geçirin; sapma varsa kök neden aynı hafta atanmış sorumluyla kapatılsın." },
    { type: "p", text: "Churn yönetimi sürekli iyileştirme döngüsüdür; on taktik tek seferlik proje değildir." },
    { type: "p", text: "Operasyonel olgunluk, abone sayısından önce metrik disipliniyle ölçülür; dashboard yoksa büyüme tesadüfidir." },
    { type: "p", text: "RELY Subs ile Craftgate/İyzico tahsilat, dunning ve storefront entegrasyonu canlıya alındıktan sonra aynı metrikleri 30 gün izleyip hedef revize edin." },
    { type: "p", text: "Son not: bu içerik operatör perspektifindedir; metrik tanımlarınızı şirket içinde sabitleyin ve çeyreklik olarak güncelleyin." },
    { type: "p", text: "Abonelik büyümesi, tekrarlayan gelir metriklerinde sürdürülebilir iyileşme gösterdiğinde gerçektir; kısa vadeli kampanya spike'ları MRR tabanını oluşturmaz." },
    { type: "p", text: "Checklist maddelerini tamamladığınızda MRR bridge ve cohort retention raporunu yönetimle paylaşın; bir sonraki çeyrek hedefleri bu tabloya göre belirlenir." },
    { type: "p", text: "RELY Subs operasyon paneli bu süreçleri Shopify ve İkas ile hizalar." },
    { type: "p", text: "Metrik disiplini abonelik olgunluğunun ön koşuludur; dashboard olmadan ölçekleme yapmayın." },
    { type: "p", text: "Churn yönetimi sürekli ölçüm ve müdahale gerektirir; tek seferlik kampanya ile düşmez." },
    { type: "p", text: "Net MRR churn hedefi her çeyrek düzenli güncellenir." },
  ] satisfies BlogPostSection[],
  checklist: [
    "Voluntary / involuntary churn dashboard ayrımı yapın",
    "Duraklatma özelliğini storefront’ta aktif edin",
    "İki adımlı iptal + kurtarma tekliflerini A/B test edin",
    "Dunning retry ve kart güncelleme akışını gözden geçirin",
    "Yenileme öncesi değer e-postası/SMS şablonu oluşturun",
    "2. ay expansion upsell kampanyası tanımlayın",
    "Ön ödemeli planları PDP’de konumlandırın",
    "Churn risk segmenti için proaktif destek kuralı yazın",
    "Lojistik SLA ihlali → churn kök neden analizi bağlayın",
    "Aylık cohort churn raporunu yönetime sunun",
    "Churn nedeni kodlarını destek CRM’ine ekleyin",
    "Net MRR churn hedefi (%3 altı olgunluk) belirleyin",
  ],
};
