import type { BlogPostSection } from "@/content/blog/types";

export const articleBody = {
  sections: [
    {
      type: "p",
      text: "Kahve, takviye (supplement) ve kozmetik, Türkiye D2C abonelik ekonomisinin omurgasıdır: üçünde de tüketim ritmi, tekrar sipariş motivasyonu ve rutin oluşturma güçlüdür. Shopify markaları bu dikeylerde aboneliğe geçerken benzer büyüme mantığı, farklı operasyon riskleri görür. Bu yazı, üç dikeyi operatör lensiyle karşılaştırır: neden abonelik, iş etkisi, örnekler, hatalar ve metrikler.",
    },
    {
      type: "h2",
      text: "Neden bu üç dikey aboneliğe uygun?",
    },
    {
      type: "h3",
      text: "Tüketim ritmi ve «unutma» problemi",
    },
    {
      type: "p",
      text: "Kahve bitiyor, vitamin kutusu boşalıyor, serum tükeniyor — müşteri acısı düşük ama sürtünme yüksek. Abonelik «bir kez ayarla, rutin kalsın» vaadi satar. Tek seferlikte müşteri başına yıllık sipariş sayısı düşük kalır; abonelik teslimat sayısını ve LTV’yi artırır.",
    },
    {
      type: "h3",
      text: "İş etkisi: MRR, LTV ve lojistik",
    },
    {
      type: "p",
      text: "Üç dikeyde de MRR öngörülebilirliği stok ve kavurma/üretim planlamasını iyileştirir. Kahvede taze ürün vaadi, supplement’te lot ve raf ömrü, kozmetikte rutin set tüketimi churn’ü yönetilebilir kılar. Lojistik: kahve hafif, pet/supplement ağır olabilir; kozmetik iade riski yüksek.",
    },
    {
      type: "h2",
      text: "Kahve dikeyi",
    },
    {
      type: "p",
      text: "Özel kavurma markaları çeşit rotasyonu ile churn’ü kırar. 250–500 g paket, 14–30 gün periyot yaygın. Shopify + RELY storefront ile sıklık değişimi; Craftgate token ile otomatik tahsilat. Hata: tek boy 1 kg abonelik — ritim uymaz, iptal artar.",
    },
    {
      type: "p",
      text: "Örnek: Yıllık 1,3 sipariş → 14 günde bir abonelik = 12 teslimat; kargo birim maliyeti %25+ düşüş, MRR tabanı oluştu.",
    },
    {
      type: "h2",
      text: "Takviye ve wellness dikeyi",
    },
    {
      type: "p",
      text: "30–45 günlük kullanım döngüsü plan periyoduna yansır. Regülasyon ve etiket değişimi operasyon yükü. İlk ay deneme kutusu + tam boy 2. ay, CAC payback hızlandırır. Başarısız ödeme oranı yüksek olabilir; dunning şart.",
    },
    {
      type: "p",
      text: "Örnek: İndirimli giriş cohort’u ayrı izlendi; 90 günlük LTV tam fiyat cohort’un %78’i — edinme stratejisi revize edildi.",
    },
    {
      type: "h2",
      text: "Kozmetik dikeyi",
    },
    {
      type: "p",
      text: "Rutin set (temizleme–serum–nem) abonelikte güçlü; renk makyajı zayıf. 60–90 günlük periyot cilt döngüsü anlatımıyla uyumlu. İade ve hassas cilt şikâyetleri voluntary churn kaynağı; destek ve içerik kritik.",
    },
    {
      type: "p",
      text: "Örnek: Üç aylık ön ödemeli rutin plan; pause ile «tatil» iptalleri %14 azaldı, LTV/CAC 3,2’ye çıktı.",
    },
    {
      type: "h2",
      text: "Üç dikeyde ortak stratejiler",
    },
    {
      type: "ul",
      items: [
        "Tek seferlik kanalı koruyup aboneliği varsayılan CTA yapmak",
        "Ön ödemeli plan ile nakit ve churn dengesi",
        "Müşteri paneli: sıklık, duraklatma, kart güncelleme",
        "Cohort retention ve LTV/CAC kanal bazında",
        "Expansion: çapraz ürün ve plan yükseltme",
      ],
    },
    {
      type: "h2",
      text: "Dikeye özel riskler",
    },
    {
      type: "p",
      text: "Kahve: tazelik ve kargo gecikmesi. Supplement: regülasyon, lot, ağır kargo. Kozmetik: iade, ton/alerji, yüksek beklenti. Her biri churn nedeni kodlarında ayrı görünmeli.",
    },
    {
      type: "h2",
      text: "RELY Subs: üç dikeyde ortak altyapı",
    },
    {
      type: "p",
      text: "Shopify veya İkas entegrasyonu, Craftgate/İyzico token’lı tahsilat, dunning, e-posta ve SMS bildirimleri ve müşteri storefront’u — kahve, supplement ve kozmetik için aynı motor, farklı plan ve mesaj. Headless yapı marka temasını korur; dikey özelleştirme plan ve içerikte yapılır.",
    },
    {
      type: "h2",
      text: "İzlenmesi gereken metrikler",
    },
    {
      type: "ul",
      items: [
        "Dikey bazlı MRR ve ARPU",
        "Teslimat başına lojistik maliyet",
        "60/90 gün cohort retention",
        "Voluntary churn nedeni (ürün / fiyat / ritim)",
        "Involuntary churn ve recovery rate",
        "Expansion MRR payı",
        "LTV/CAC edinme kanalına göre",
      ],
    },
    {
      type: "p",
      text: "Kahve, takviye ve kozmetik markaları aboneliğe «moda» olduğu için değil, tekrarlayan gelir ve LTV matematiği işlediği için geçiyor. Operatör farkı, dikey riskleri bilerek aynı altyapıyı disiplinle yönetmektir.",
    },
    {
      type: "h2",
      text: "Dikey karşılaştırma tablosu (operatör özeti)",
    },
    {
      type: "p",
      text: "Kahve: yüksek frekans, düşük iade, tazelik kritik. Supplement: orta frekans, regülasyon, yüksek involuntary churn riski. Kozmetik: orta–düşük frekans, yüksek voluntary churn (beklenti), iade hassas. Üçünde de abonelik LTV’yi tek seferlikten yukarı çeker; operasyon yükü dikeye göre kalibre edilir.",
    },
    {
      type: "h2",
      text: "Pazarlama ve teklif farkları",
    },
    {
      type: "p",
      text: "Kahvede «taze kavurma tarihi» ve çeşit keşfi; supplement’te «rutin tamamlama» ve hedef (uyku, enerji); kozmetikte «cilt döngüsü» ve görünür sonuç. Aynı indirim mesajı üç dikeyde çalışmaz.",
    },
    {
      type: "p",
      text: "Influencer ve UGC içerik abonelik dönüşümünü artırır; ancak indirim kodu ile gelen düşük niyetli aboneler 2. ay churn’ü şişirir. Kod bazlı cohort ayrı izlenmelidir.",
    },
    {
      type: "h2",
      text: "Ölçek aşamasında dikey disiplin",
    },
    {
      type: "p",
      text: "10.000+ abone: kahvede kavurma kapasitesi, supplement’te lot ve depo, kozmetikte iade ve müşteri hizmetleri ölçeklenir. RELY Subs plan ve bildirim otomasyonu manuel yükü azaltır; dikey uzmanlık ürün ve mesajda kalır.",
    },
    {
      type: "p",
      text: "Çok dikeyli holding markası tek abonelik checkout’ta üç dikeyi birleştirmemeli; marka başına net storefront ve plan ağacı churn’ü düşürür.",
    },
    { type: "h2", text: "Lojistik ve maliyet karşılaştırması" },
    { type: "p", text: "Kahve: hafif paket, sık teslimat, düşük iade. Supplement: ağır paket, orta frekans, yüksek kargo oranı — büyük kutu aboneliği birim maliyeti düşürür. Kozmetik: küçük paket ama iade ve destek maliyeti yüksek." },
    { type: "p", text: "Üç dikeyde de ARPU artırmak için ön ödemeli plan ve büyük boy SKU tercih edilir; operasyon bunu plan ağacında yansıtır." },
    { type: "h2", text: "Edinme kanalı ve LTV" },
    { type: "p", text: "Instagram Reels kahve ve kozmetikte dönüşüm getirir; supplement’te arama ve influencer karışımı. Kanal bazlı 90 günlük LTV aynı değil; bütçe dikeye göre bölünür." },
    { type: "h3", text: "Mevsim ve kampanya etkisi" },
    { type: "p", text: "Kahvede yılbaşı hediye tek seferlik spike; abonelik «kendi rutinim» mesajı ile korunur. Kozmetikte 11.11 indirimi abonelikten ayrı tutulmalı; indirimli tek seferlik cohort churn’ü aboneliği kirletmez." },
    { type: "p", text: "Takviyede «Ocak detox» kampanyası abonelik girişi için köprü olabilir; 60 günlük plan ile bağlanır." },
    { type: "h2", text: "Uzun vadeli marka değeri" },
    { type: "p", text: "Abonelik, üç dikeyde de markayı «günlük rutin» kategorisine taşır; tek seferlik hediye algısından çıkar. NPS ve destek verisi dikey bazlı okunmalı; tek NPS yanıltır." },
    { type: "h2", text: "Birleşik operasyon paneli" },
    { type: "p", text: "Üç dikeyde de aynı RELY paneli: plan, dunning, storefront; dikey farkı plan şablonları ve mesaj kütüphanesinde. Operasyon ekibi dikey uzmanlık, teknoloji tek altyapı." },
    { type: "p", text: "Kahve markası supplement upsell yapabilir; ayrı abonelik planı, tek kutuda karışım değil." },
    { type: "p", text: "Kozmetik markası «yaz güneş koruyucu» tek seferlik, rutin serum abonelik — sezon SKU’su plan dışı." },
    { type: "p", text: "Benchmark: Türkiye D2C’de kahve abonelik penetrasyonu supplement’e göre daha olgun; kozmetik hızla büyüyor — beklenti yönetimi kritik." },
    { type: "p", text: "2026’da üç dikeyde de CAC baskısı altında abonelik, tekrarlayan gelir güvenli liman olarak konumlanır." },
    { type: "h2", text: "Üç dikeyde ortak sonuç" },
    { type: "p", text: "Kahve, takviye ve kozmetik markaları aboneliğe, tekrarlayan gelir ve LTV matematiği için geçiyor. Operasyonel farklar ritim, regülasyon, iade ve kargo; ortak ihtiyaç token’lı tahsilat, dunning, müşteri paneli ve cohort disiplini." },
    { type: "p", text: "RELY Subs üç dikeyde de aynı altyapıyı sunar; dikey uzmanlık plan ve mesajda kalır. Tek seferlik kanal korunur, abonelik varsayılan büyüme motoru olur." },
    { type: "p", text: "Metrikler dikey bazlı okunmalı; tek churn oranı yanıltır. Doğru kurguda MRR öngörülebilir, stok planlanabilir, CAC geri ödemesi hızlanır." },
    { type: "p", text: "Private label ve white label markalar da aynı dikey dinamiklere tabidir; marka hikâyesi churn’ü düşürür." },
    { type: "p", text: "Operatör notu: metrik tanımlarını ekip içi wiki’de kilitleyin; yeni çalışan onboarding’inde aynı LTV/MRR/churn sözlüğü kullanılsın." },
    { type: "p", text: "Shopify Flow veya harici otomasyon, RELY webhook’larıyla çakışmamalı; çift e-posta müşteri güvenini zedeler." },
    { type: "p", text: "Büyüme toplantısında «bu ay kaç abone» yerine «net MRR ne kadar büyüdü, churn nedenleri ne» sorulmalıdır." },
    { type: "p", text: "Türkiye’de kargo performansı abonelik NPS’ini doğrudan etkiler; lojistik partner quarterly review abonelik KPI’sına bağlanmalıdır." },
    { type: "p", text: "RELY Subs müşteri storefront’u mobil trafiğe göre optimize edilmeli; kart güncelleme ve pause işlemleri üç tıkta tamamlanmalıdır." },
    { type: "p", text: "Dikeyler arası öğrenme: kahvedeki tazelik mesajı supplement’te «taze lot», kozmetikte «yeni formül ama aynı rutin» olarak uyarlanır." },
    { type: "p", text: "Kahve dikeyinde B2B ofis aboneliği ayrı plan ailesi olabilir; tüketim hızı farklıdır." },
    { type: "p", text: "Supplement'te sağlık iddiası içerikleri regülasyon gerektirir; abonelik e-postasında dikkat." },
    { type: "p", text: "Kozmetikte influencer kodu ile gelen aboneler ayrı cohort; LTV düşükse kanal kesilir." },
    { type: "p", text: "Üç dikeyde de sürdürülebilir ambalaj abonelik churn'ünü düşürebilir; marka hikâyesi." },
    { type: "p", text: "Abonelik, D2C markasını «transactional»den «relational» modele taşır; bu stratejik sıçramadır." },
    { type: "p", text: "Üç dikeyde de abonelik, tekrarlayan gelir ve LTV için mantıklıdır; operasyon farklarını bilerek RELY + Shopify/İkas ile ölçekleyin." },
    { type: "p", text: "Operatörler için altın kural: abonelik metrikleri (MRR, churn, LTV, recovery) tek tanımlı dashboard'da haftalık okunur; Excel dağınıklığı karar geciktirir." },
    { type: "p", text: "Türkiye ödeme ve kargo gerçekleri, global abonelik playbook'unu olduğu gibi kopyalamayı engeller; yerel token, SMS ve SLA ile kalibre edin." },
    { type: "p", text: "RELY Subs, Shopify ve İkas mağazanıza headless abonelik katmanı ekler; Craftgate ve İyzico tahsilat, dunning ve müşteri storefront'u operasyonu tekilleştirir." },
    { type: "p", text: "Kahve aboneliğinde «çeşit keşfi» her 3. teslimatta rotasyon voluntary churn'ü düşürür." },
    { type: "p", text: "Supplement aboneliğinde sağlık profesyoneli içeriği (diyetisyen Q&A) güven ve LTV artırır." },
    { type: "p", text: "Kozmetik aboneliğinde mini boy «travel size» ek kutusu upsell expansion MRR üretir." },
    { type: "p", text: "Dikey bazlı affiliate ve influencer anlaşmaları ayrı LTV cohort'u olarak izlenir." },
    { type: "p", text: "Bu rehberdeki taktikler, Shopify ve İkas üzerinde çalışan D2C abonelik operatörleri için saha deneyimine dayanır; metrik tanımlarınızı ekip içinde sabitleyip RELY Subs paneli ile haftalık ritim kurduğunuzda MRR, LTV ve recovery birlikte iyileşir. Tek seferlik satışa göre abonelikte kazanç, öngörülebilir taban gelir ve düşük net churn'de görünür." },
    { type: "p", text: "Özet: Kahve, supplement ve kozmetik aboneliğe tüketim ritmi ve LTV için uygundur; dikey riskler farklı, altyapı ortaktır. RELY + Shopify/İkas ile plan, tahsilat ve storefront tek panelden yönetilir." },
    { type: "p", text: "Checklist maddelerini 30 günlük sprint'e bölün; sahip atayın; haftalık durum toplantısında MRR bridge ve churn nedeni okunur." },
    { type: "p", text: "Shopify D2C operatörü olarak abonelik, «eklenti» değil iş modeli katmanıdır; metrik disiplini olmadan büyüme sürdürülemez." },
    { type: "p", text: "Pazarlama, finans ve operasyon aynı toplantıda MRR hareket tablosunu okumadığında abonelik projesi parçalanır; haftalık 30 dakika «abonelik council» bu riski azaltır." },
    { type: "p", text: "Türkiye'de SMS ve e-posta birlikte kullanıldığında recovery ve churn müdahalesi güçlenir; yalnızca e-posta tek başına yetersiz kalır." },
    { type: "p", text: "RELY Subs: Shopify/İkas ürün ve sipariş senkronu, Craftgate/İyzico token tahsilatı, dunning, e-posta ve SMS bildirimleri ve müşteri storefront — operatörün tekrarlayan gelir altyapısı tek panelde toplanır." },
    { type: "p", text: "Yazı sonu hatırlatma: abonelik operasyonunda ölçmediğiniz metrik yönetemezsiniz; MRR bridge, cohort LTV, voluntary/involuntary churn ayrımı ve recovery rate dörtlüsü olmadan büyüme kararları kör kalır. RELY Subs bu dörtlüyü destekleyen headless katmandır — mevcut Shopify veya İkas mağazanızı değiştirmeden tekrarlayan gelir disiplinini kurun." },
    { type: "p", text: "Uygulama checklist'indeki maddeleri öncelik sırasına koyun; ilk 14 günde ödeme ve metrik altyapısı, sonraki 30 günde churn ve LTV müdahaleleri devreye girsin." },
    { type: "p", text: "İleri okuma: MRR bridge ve cohort retention raporlarını aylık kapanışta finans ve pazarlama ile birlikte gözden geçirin; sapma varsa kök neden aynı hafta atanmış sorumluyla kapatılsın." },
    { type: "p", text: "Dikey seçimi marka kimliğinizle uyumlu olmalı; abonelik rutin satışı derinleştirir." },
    { type: "p", text: "Operasyonel olgunluk, abone sayısından önce metrik disipliniyle ölçülür; dashboard yoksa büyüme tesadüfidir." },
    { type: "p", text: "RELY Subs ile Craftgate/İyzico tahsilat, dunning ve storefront entegrasyonu canlıya alındıktan sonra aynı metrikleri 30 gün izleyip hedef revize edin." },
    { type: "p", text: "Son not: bu içerik operatör perspektifindedir; metrik tanımlarınızı şirket içinde sabitleyin ve çeyreklik olarak güncelleyin." },
    { type: "p", text: "Abonelik büyümesi, tekrarlayan gelir metriklerinde sürdürülebilir iyileşme gösterdiğinde gerçektir; kısa vadeli kampanya spike'ları MRR tabanını oluşturmaz." },
    { type: "p", text: "Checklist maddelerini tamamladığınızda MRR bridge ve cohort retention raporunu yönetimle paylaşın; bir sonraki çeyrek hedefleri bu tabloya göre belirlenir." },
    { type: "p", text: "RELY Subs operasyon paneli bu süreçleri Shopify ve İkas ile hizalar." },
  ] satisfies BlogPostSection[],
  checklist: [
    "Dikeyinize uygun plan periyodu (gün/ay) belirleyin",
    "Tek seferlik + abonelik PDP hiyerarşisini test edin",
    "Taze ürün / lot / rutin mesajını değer önerisine yazın",
    "Duraklatma ve sıklık değişimini storefront’ta açın",
    "Dunning ve recovery KPI set edin (supplement/kahve)",
    "Kozmetik için iade ve hassas cilt SSS hazırlayın",
    "Cohort LTV’yi dikey benchmark ile karşılaştırın",
    "Lojistik birim maliyeti dikey raporu aylık izleyin",
    "Churn nedeni kodlarını dikeye özel tanımlayın",
    "RELY/Shopify senkron ve webhook sağlık kontrolü yapın",
    "Ön ödemeli plan payı hedefi koyun (%20+)",
    "Expansion upsell’i 2. teslimat sonrası tetikleyin",
  ],
};
