import type { BlogPostSection } from "@/content/blog/types";

export const articleBody = {
  sections: [
    {
      type: "p",
      text: "Shopify mağazasında abonelik modeli kurmak, bir uygulama kurmaktan ibaret değildir: ürün yapısı, ödeme tokenization, müşteri paneli, stok senkronu ve destek süreçleri aynı anda tasarlanmalıdır. Türkiye’de Craftgate/İyzico ile tekrarlayan tahsilat, İkas alternatifi ve headless abonelik katmanı (RELY Subs) gibi seçenekler varken «Shopify’da açtık» demek yeterli değildir. Bu rehber, abonelik öncesi operatör kontrol listesidir.",
    },
    {
      type: "h2",
      text: "Neden ön hazırlık atlanınca proje çöker?",
    },
    {
      type: "h3",
      text: "İş etkisi: MRR ve operasyon borcu",
    },
    {
      type: "p",
      text: "Hazırlıksız lansman, yüksek 2. ay churn ve manuel tahsilat operasyonu üretir. Teknik borç (çift sipariş, stok uyumsuzluğu) büyüdükçe MRR büyümesi durur; ekip «yangın söndürme» moduna geçer. İlk 90 gün tasarım yatırımı, sonraki 12 ay ölçek maliyetini belirler.",
    },
    {
      type: "p",
      text: "Shopify Analytics toplam ciro gösterir; abonelik MRR ayrı tanım gerektirir. Yönetim tek rakama bakarsa abonelik yatırımı erken kesilir.",
    },
    {
      type: "h2",
      text: "Ürün ve katalog hazırlığı",
    },
    {
      type: "h3",
      text: "Hangi SKU’lar aboneliğe girer?",
    },
    {
      type: "p",
      text: "Tüketim ritmi net, marjı sağlıklı, kargo ağırlığı yönetilebilir SKU’lar seçilir. Tüm katalog abonelik yapılmaz. PDP’de abonelik ve tek seferlik CTA hiyerarşisi net: varsayılan abonelik, ikincil tek seferlik.",
    },
    {
      type: "h3",
      text: "Plan periyotları ve fiyat",
    },
    {
      type: "p",
      text: "30/60/90 gün ve ön ödemeli yıllık planlar; nakit akışı ve churn dengesi. İlk ay indirimi cohort olarak izlenir; kalıcı ARPU sanılmaz. Vergi ve KDV gösterimi tutarlı olmalı.",
    },
    {
      type: "h2",
      text: "Ödeme ve tahsilat mimarisi",
    },
    {
      type: "p",
      text: "Türkiye’de abonelik için token’lı tekrarlayan ödeme şarttır. Craftgate veya İyzico ile kart saklama; RELY’de kart tutulmaz. 3D Secure ve retry kuralları önceden test edilir. Manuel «her ay ödeme linki» 300 aboneden sonra ölçeklenmez.",
    },
    {
      type: "p",
      text: "Başarılı tahsilat → sipariş oluşturma sırası net: ödeme başarısızken Shopify’da sipariş açmak stok ve müşteri şikâyeti üretir.",
    },
    {
      type: "h2",
      text: "Entegrasyon: Shopify ve abonelik motoru",
    },
    {
      type: "p",
      text: "API token, webhook sağlığı, ürün/varyant senkronu, iptal ve iade akışı dokümante edilir. Headless RELY Subs, mevcut tema korunurken abonelik checkout ve müşteri paneli sağlar; Shopify sipariş geçmişi senkron kalır. İkas kullanan markalar için aynı mantık API anahtarıyla uygulanır.",
    },
    {
      type: "h2",
      text: "Müşteri deneyimi ve storefront",
    },
    {
      type: "p",
      text: "Abone «hesabım»da sıklık değişimi, duraklatma, adres güncelleme, kart güncelleme olmalı. Destek yükü burada düşer. Bildirimler (e-posta ve SMS): yenileme öncesi, başarısız ödeme, kargo — marka tonunda.",
    },
    {
      type: "h2",
      text: "Operasyon ve lojistik",
    },
    {
      type: "p",
      text: "Yenileme takvimi depo pick-pack girdisi olur. Kargo SLA abonelik hacmine göre yeniden müzakere edilir. İade politikası abonelik için ayrı maddeler içerir (açılmış ürün vb.).",
    },
    {
      type: "h2",
      text: "Gerçek senaryo",
    },
    {
      type: "p",
      text: "Shopify Plus kahve markası: Abonelik eklentisi + manuel ödeme üç ayda 420 abone sonra operasyon çöktü. RELY Subs + Craftgate token + storefront sonrası recovery rate %36, destek talebi %31 azaldı, MRR bridge netleşti.",
    },
    {
      type: "h2",
      text: "Yaygın hatalar",
    },
    {
      type: "ul",
      items: [
        "Ödeme altyapısını lansman sonrasına bırakmak",
        "MRR tanımı olmadan büyüme hedefi koymak",
        "Tüm kataloğu aboneliğe açmak",
        "Müşteri paneli olmadan scale etmek",
        "Churn’ü tek kalem raporlamak",
        "Shopify siparişi ile tahsilat sırasını karıştırmak",
      ],
    },
    {
      type: "h2",
      text: "İzlenmesi gereken metrikler (lansman öncesi baseline)",
    },
    {
      type: "ul",
      items: [
        "Tekrar sipariş oranı (mevcut müşteri)",
        "Ortalama sipariş aralığı (gün)",
        "Brüt marj SKU bazında",
        "Destek talebi / 1000 sipariş",
        "Kargo birim maliyeti",
        "Mevcut CAC ve 90 günlük LTV (tek seferlik)",
      ],
    },
    {
      type: "p",
      text: "Shopify’da abonelik, mağazaya modül eklemek değil; tekrarlayan gelir işletmesi kurmaktır. Ön hazırlık tamamlandığında lansman MRR büyümesine, değilse teknik borca odaklanır.",
    },
    {
      type: "h2",
      text: "Teknik kontrol listesi (Shopify operatör)",
    },
    {
      type: "p",
      text: "Admin API erişimi, webhook endpoint sağlığı, sipariş/iptal/iade event’leri, envanter senkron gecikmesi ölçülmeli. Staging mağazada test aboneliği: oluştur, yenile, başarısız öde, duraklat, iptal — her adımda Shopify sipariş durumu doğrulanmalıdır.",
    },
    {
      type: "p",
      text: "Tema güncellemeleri headless storefront’u etkilemez; yine de checkout linkleri ve müşteri paneli URL’leri dokümante edilmelidir.",
    },
    {
      type: "h2",
      text: "Ekip ve SLA hazırlığı",
    },
    {
      type: "p",
      text: "Destek ekibi abonelik SSS, iptal makroları ve «kart güncelleme» yönlendirmesi eğitimi almalıdır. Depo SLA yenileme günü yoğunluğuna göre revize edilir. Finans MRR bridge sorumlusu atanır.",
    },
    {
      type: "h3",
      text: "Lansman KPI’ları",
    },
    {
      type: "p",
      text: "İlk 90 gün: yeni abone MRR, 60 günlük retention, recovery rate, voluntary churn nedeni dağılımı. «Toplam ciro» ikincil KPI kalır. Hedefler lansman öncesi yazılır; 30. günde revize edilir.",
    },
    {
      type: "h2",
      text: "İkas ve çok kanallı mağaza notları",
    },
    {
      type: "p",
      text: "İkas kullanan markalarda Shopify ile aynı hazırlık geçerlidir: API anahtarı, ürün eşlemesi, sipariş yansıması. Çok kanallı satışta hangi kanalın abonelik master olduğu netleştirilmelidir; çift stok kaydı önlenir.",
    },
    {
      type: "p",
      text: "RELY Subs her iki platformda da aynı abonelik mantığını korur; operasyon ekibi tek panelden plan ve tahsilat yönetir.",
    },
    { type: "h2", text: "Ürün sayfası ve dönüşüm mimarisi" },
    { type: "p", text: "Abonelik PDP’sinde «tek seferlik» ikincil; fiyat karşılaştırması yıllık maliyet yerine «teslimat başına» veya «günlük maliyet» çerçevesi kullanılabilir. Sosyal kanıt: abone sayısı, teslimat sıklığı yorumları." },
    { type: "p", text: "Checkout’ta sürpriz kargo veya vergi, 2. yenilemede churn üretir; tüm maliyetler ilk ekranda." },
    { type: "h2", text: "Güvenlik ve uyumluluk" },
    { type: "p", text: "Kart verisi Shopify’da değil, ödeme kuruluşunda; RELY PCI yükünü taşımaz. Gizlilik politikası otomatik yenilemeyi açık anlatmalıdır." },
    { type: "h3", text: "Test senaryoları (lansman öncesi)" },
    { type: "p", text: "Test kartı ile: başarılı yenileme, red, 3DS, kart süresi dolmuş simülasyonu, duraklatma, iptal, iade. Her senaryoda Shopify sipariş ve stok doğrulaması." },
    { type: "p", text: "Webhook gecikmesi ve duplicate event senaryosu; idempotent sipariş oluşturma kritik." },
    { type: "h2", text: "Büyüme sonrası ikinci dalga hazırlık" },
    { type: "p", text: "Lansman sonrası 500 abone: destek headcount ve depo gözden geçirilir. 2.000 abone: kargo anlaşması yeniden müzakere. Abonelik «proje» değil sürekli ürün sahipliği (owner) atanır." },
    { type: "h2", text: "İç ekip alignment workshop" },
    { type: "p", text: "Lansman öncesi tek günlük workshop: pazarlama teklifi, finans MRR tanımı, operasyon SLA, teknoloji test sonuçları. Çıktı: yazılı lansman playbook." },
    { type: "p", text: "Shopify Plus ise B2B veya çoklu mağaza senaryosu ayrı değerlendirilir; abonelik master mağaza netleşir." },
    { type: "p", text: "İkas migrasyonu planlanan markada çift yazım dönemi kısa tutulur; abonelik yalnızca stabil entegrasyon sonrası açılır." },
    { type: "p", text: "Müşteri hizmetleri «abonelik değil tek seferlik» talebini azaltmak için PDP ve SSS önceden güncellenir." },
    { type: "p", text: "Lansman haftası günlük MRR ve failed payment izleme — erken müdahale cohort’u kurtarır." },
    { type: "h2", text: "Lansman sonrası ilk 30 gün" },
    { type: "p", text: "Günlük: yeni MRR, failed payment kuyruğu, webhook hata logu. Haftalık: cohort retention, churn nedeni, destek ticket trendi. 30. gün: go/no-go — ölçekleme veya teklif revizyonu." },
    { type: "p", text: "Shopify mağazasında abonelik, hazırlık kalitesiyle kazanılır. Ödeme, ürün, panel, operasyon ve metrik tanımı lansmandan önce oturmalıdır." },
    { type: "p", text: "RELY Subs ile headless katman, temayı bozmadan abonelik deneyimini ekler; operatör tek panelden plan ve tahsilat yönetir." },
    { type: "p", text: "Shopify Markets çok ülke senaryosunda abonelik ve ödeme kuralları ülke bazlı ayrılır; lansman öncesi kapsam netleşir." },
    { type: "p", text: "Operatör notu: metrik tanımlarını ekip içi wiki’de kilitleyin; yeni çalışan onboarding’inde aynı LTV/MRR/churn sözlüğü kullanılsın." },
    { type: "p", text: "Shopify Flow veya harici otomasyon, RELY webhook’larıyla çakışmamalı; çift e-posta müşteri güvenini zedeler." },
    { type: "p", text: "Büyüme toplantısında «bu ay kaç abone» yerine «net MRR ne kadar büyüdü, churn nedenleri ne» sorulmalıdır." },
    { type: "p", text: "Türkiye’de kargo performansı abonelik NPS’ini doğrudan etkiler; lojistik partner quarterly review abonelik KPI’sına bağlanmalıdır." },
    { type: "p", text: "RELY Subs müşteri storefront’u mobil trafiğe göre optimize edilmeli; kart güncelleme ve pause işlemleri üç tıkta tamamlanmalıdır." },
    { type: "p", text: "Shopify Partner veya ajans ile çalışıyorsanız, abonelik scope’u SOW’da açık yazılmalıdır: yalnızca tema değil, ödeme ve operasyon dahil." },
    { type: "p", text: "Lansman öncesi 10 gerçek müşteriyle beta (ücretsiz veya indirimli) webhook ve bildirim hatalarını yakalar." },
    { type: "p", text: "Shopify app conflict kontrolü: eski abonelik uygulaması kaldırılmadan RELY bağlanmaz; çift tahsilat riski." },
    { type: "p", text: "Fulfillment app (kargo entegrasyonu) abonelik sipariş etiketini tanımalıdır." },
    { type: "p", text: "Muhasebe yazılımı (Paraşüt, Logo vb.) abonelik gelir tahakkuku için hazırlık." },
    { type: "p", text: "İçerik ekibi: abonelik landing, SSS, iptal politikası sayfaları lansman öncesi yayında." },
    { type: "p", text: "C-level beklentisi: ilk 6 ay MRR eğrisi, brüt ciro değil ana slayt olmalıdır." },
    { type: "p", text: "Shopify abonelik yolculuğu ön hazırlıkla kazanılır; lansman sonrası yangın söndürmek yerine checklist ile ilerleyin. RELY headless katman mevcut mağazayı korur." },
    { type: "p", text: "Operatörler için altın kural: abonelik metrikleri (MRR, churn, LTV, recovery) tek tanımlı dashboard'da haftalık okunur; Excel dağınıklığı karar geciktirir." },
    { type: "p", text: "Türkiye ödeme ve kargo gerçekleri, global abonelik playbook'unu olduğu gibi kopyalamayı engeller; yerel token, SMS ve SLA ile kalibre edin." },
    { type: "p", text: "RELY Subs, Shopify ve İkas mağazanıza headless abonelik katmanı ekler; Craftgate ve İyzico tahsilat, dunning ve müşteri storefront'u operasyonu tekilleştirir." },
    { type: "p", text: "Shopify checkout extensibility veya standart checkout — abonelik CTA'sının nereye oturacağı lansman öncesi karar." },
    { type: "p", text: "Stok buffer: abonelik için güvenlik stoğu formülü depo ile paylaşılır." },
    { type: "p", text: "Hukuk: otomatik yenileme ve mesafeli satış metinleri güncellenir." },
    { type: "p", text: "Beta cohort'tan gelen geri bildirim PDP ve panelde lansman öncesi uygulanır." },
    { type: "p", text: "Bu rehberdeki taktikler, Shopify ve İkas üzerinde çalışan D2C abonelik operatörleri için saha deneyimine dayanır; metrik tanımlarınızı ekip içinde sabitleyip RELY Subs paneli ile haftalık ritim kurduğunuzda MRR, LTV ve recovery birlikte iyileşir. Tek seferlik satışa göre abonelikte kazanç, öngörülebilir taban gelir ve düşük net churn'de görünür." },
    { type: "p", text: "Özet: Shopify aboneliği lansman öncesi ürün, ödeme, entegrasyon, panel, operasyon ve metrik hazırlığı ister; checklist tamamlanmadan ölçekleme yapmayın. RELY headless katman mevcut temayı korur." },
    { type: "p", text: "Checklist maddelerini 30 günlük sprint'e bölün; sahip atayın; haftalık durum toplantısında MRR bridge ve churn nedeni okunur." },
    { type: "p", text: "Shopify D2C operatörü olarak abonelik, «eklenti» değil iş modeli katmanıdır; metrik disiplini olmadan büyüme sürdürülemez." },
    { type: "p", text: "Pazarlama, finans ve operasyon aynı toplantıda MRR hareket tablosunu okumadığında abonelik projesi parçalanır; haftalık 30 dakika «abonelik council» bu riski azaltır." },
    { type: "p", text: "Türkiye'de SMS ve e-posta birlikte kullanıldığında recovery ve churn müdahalesi güçlenir; yalnızca e-posta tek başına yetersiz kalır." },
    { type: "p", text: "RELY Subs: Shopify/İkas ürün ve sipariş senkronu, Craftgate/İyzico token tahsilatı, dunning, e-posta ve SMS bildirimleri ve müşteri storefront — operatörün tekrarlayan gelir altyapısı tek panelde toplanır." },
    { type: "p", text: "Yazı sonu hatırlatma: abonelik operasyonunda ölçmediğiniz metrik yönetemezsiniz; MRR bridge, cohort LTV, voluntary/involuntary churn ayrımı ve recovery rate dörtlüsü olmadan büyüme kararları kör kalır. RELY Subs bu dörtlüyü destekleyen headless katmandır — mevcut Shopify veya İkas mağazanızı değiştirmeden tekrarlayan gelir disiplinini kurun." },
    { type: "p", text: "Uygulama checklist'indeki maddeleri öncelik sırasına koyun; ilk 14 günde ödeme ve metrik altyapısı, sonraki 30 günde churn ve LTV müdahaleleri devreye girsin." },
    { type: "p", text: "İleri okuma: MRR bridge ve cohort retention raporlarını aylık kapanışta finans ve pazarlama ile birlikte gözden geçirin; sapma varsa kök neden aynı hafta atanmış sorumluyla kapatılsın." },
    { type: "p", text: "Ön hazırlık tamamsa lansman MRR büyümesine odaklanır; değilse teknik borç büyür." },
    { type: "p", text: "Operasyonel olgunluk, abone sayısından önce metrik disipliniyle ölçülür; dashboard yoksa büyüme tesadüfidir." },
    { type: "p", text: "RELY Subs ile Craftgate/İyzico tahsilat, dunning ve storefront entegrasyonu canlıya alındıktan sonra aynı metrikleri 30 gün izleyip hedef revize edin." },
    { type: "p", text: "Son not: bu içerik operatör perspektifindedir; metrik tanımlarınızı şirket içinde sabitleyin ve çeyreklik olarak güncelleyin." },
    { type: "p", text: "Abonelik büyümesi, tekrarlayan gelir metriklerinde sürdürülebilir iyileşme gösterdiğinde gerçektir; kısa vadeli kampanya spike'ları MRR tabanını oluşturmaz." },
    { type: "p", text: "Checklist maddelerini tamamladığınızda MRR bridge ve cohort retention raporunu yönetimle paylaşın; bir sonraki çeyrek hedefleri bu tabloya göre belirlenir." },
    { type: "p", text: "RELY Subs operasyon paneli bu süreçleri Shopify ve İkas ile hizalar." },
    { type: "p", text: "Metrik disiplini abonelik olgunluğunun ön koşuludur; dashboard olmadan ölçekleme yapmayın." },
    { type: "p", text: "Ön hazırlık tamamlandığında lansman, MRR büyümesine odaklanır; aksi halde operasyon sürekli yangın modunda kalır." },
  ] satisfies BlogPostSection[],
  checklist: [
    "Abonelik aday SKU listesi ve skor kartı onaylayın",
    "Craftgate/İyzico token test ortamında retry senaryolarını çalıştırın",
    "Shopify API + webhook checklist’ini tamamlayın",
    "MRR bridge şablonunu lansman öncesi oluşturun",
    "Müşteri storefront UX akışını (duraklatma, kart) test edin",
    "Dunning e-posta/SMS şablonlarını marka tonunda yazın",
    "Depo yenileme takvimi entegrasyonunu planlayın",
    "Destek ekibi abonelik SSS eğitimini verin",
    "İade ve iptal politikasını abonelik maddeleriyle güncelleyin",
    "Lansman KPI: 90 günlük cohort retention ve recovery rate",
    "İkas/Shopify hangi kanal master — dokümante edin",
    "Baseline tekrar sipariş metriklerini kaydedin",
  ],
};
